insert into dbo.List values ('Phim hay',GETDATE(),'KMB')
insert into dbo.List values ('Horror',GETDATE(),'PTD')
insert into dbo.List values ('Romcom',GETDATE(),'DVG')
insert into dbo.List values ('Holywood',GETDATE(),'NGTD')
insert into dbo.List values ('Documentary',GETDATE(),'User123')