insert into dbo.List values ('Phim hay',GETDATE(),'KMB')
insert into dbo.List values ('Horror',GETDATE(),'Scary boi')
insert into dbo.List values ('Romcom',GETDATE(),'member123')
insert into dbo.List values ('Holywood',GETDATE(),'deadline898')
insert into dbo.List values ('Documentary',GETDATE(),'Vosddis')